### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gosip**
Change outdated links to documentation.

### CODE REVIEW

**Comment by ibrahima** [comment]
Hi! Thanks for the PR, but those links work for me - the relative paths should work. Where are you seeing the links being broken or out of date?

**Comment by gosip** [comment]
Hi!
When I am at https://github.com/gradescope/autograder_samples in [the readme](https://github.com/gradescope/autograder_samples#readme) section and click on *specifications*, I get redirected to https://github.com/gradescope/autograder_samples/blob/master/specs, which appears not to be found (404). Clicking *instructions* redirects to https://github.com/gradescope/autograder_samples/blob/master/getting_started, which is not found as well.

**Comment by gosip** [comment]
If my comment was not clear enough, relative path works for gradescope-autograders.readthedocs.io, but fails for the github readme.
@ibrahima

**Comment by ibrahima** [comment]
Ah right, sorry about that. That's weird, I could have sworn I actually did the relative links in the first place so that it would work on both ReadTheDocs and the Github readme, so they might have changed something on Github to make that not work. I'll have to play around a bit to see if there's a way to keep relative links working so that Github browsers don't get sent to a different site, which could be slightly jarring. But I think for now, this PR is great so that at least the links work in both places.

**Comment by ibrahima** [comment]
Thanks for the PR!

**Pull request merged**
